/**
 * @file src/remote_microphone_diagnostics.h
 * @brief Aggregate diagnostics for remote microphone reception.
 */
#pragma once

#include <chrono>
#include <cstdint>
#include <span>

namespace remote_microphone::detail {
  /**
   * @brief Source of one PCM playout frame.
   */
  enum class microphone_frame_source_e {
    packet,  ///< Decoded received packet.
    plc,  ///< Opus packet-loss concealment.
    synthetic_zero,  ///< Locally generated silence.
  };

  /**
   * @brief Privacy-preserving counters and signal aggregates.
   */
  struct microphone_diagnostics_snapshot_t {
    std::uint64_t received {};  ///< UDP datagrams received.
    std::uint64_t accepted {};  ///< Packets admitted to the jitter queue.
    std::uint64_t rejected {};  ///< Datagrams rejected by validation or admission.
    std::uint64_t opus_mono {};  ///< Accepted Opus packets declaring mono.
    std::uint64_t opus_stereo {};  ///< Accepted Opus packets declaring stereo.
    std::uint64_t packet_frames {};  ///< Frames decoded from received packets.
    std::uint64_t plc_frames {};  ///< Frames generated by Opus loss concealment.
    std::uint64_t synthetic_zero_frames {};  ///< Frames filled locally with zeroes.
    std::uint64_t reanchors {};  ///< Forward sequence discontinuities.
    std::uint64_t jitter_overflows {};  ///< Full jitter-queue discards.
    std::uint64_t late_or_replayed {};  ///< Sequence or playout admission rejections.
    std::uint64_t skipped_frames {};  ///< Playout positions skipped after scheduling delays.
    std::uint64_t sink_drops {};  ///< Frames refused by the sink mailbox.
    std::uint64_t pcm_samples {};  ///< Samples measured from packet frames.
    std::uint64_t pcm_zero_samples {};  ///< Measured packet samples equal to zero.
    std::uint64_t pcm_clipped_samples {};  ///< Measured packet samples at integer limits.
    std::uint32_t pcm_peak {};  ///< Largest absolute packet sample in int16 units.
    long double pcm_square_sum {};  ///< Packet sample square sum for RMS.
    std::chrono::nanoseconds max_schedule_gap {};  ///< Longest receiver loop interval.
    std::chrono::milliseconds max_arrival_gap {};  ///< Longest forward-packet arrival interval.
    std::uint32_t max_client_timestamp_delta_ms {};  ///< Largest forward client timestamp delta.

    /**
     * @brief Calculate the RMS amplitude of PCM decoded from packets.
     * @return RMS amplitude in signed 16-bit sample units.
     */
    [[nodiscard]] double pcm_rms() const noexcept;

    /**
     * @brief Calculate the fraction of packet PCM samples equal to zero.
     * @return Fraction in the range zero through one.
     */
    [[nodiscard]] double pcm_zero_fraction() const noexcept;

    /**
     * @brief Calculate the fraction of packet PCM samples at either integer limit.
     * @return Fraction in the range zero through one.
     */
    [[nodiscard]] double pcm_clipped_fraction() const noexcept;
  };

  /**
   * @brief Accumulate interval and session-wide microphone diagnostics.
   */
  class microphone_diagnostics_t {
  public:
    /**
     * @brief Count one received datagram.
     */
    void record_received() noexcept;

    /**
     * @brief Count one rejected datagram.
     *
     * @param late_or_replayed Whether sequence or playout admission rejected it.
     */
    void record_rejected(bool late_or_replayed = false) noexcept;

    /**
     * @brief Count one accepted packet and its channel/timing metadata.
     *
     * @param opus Decrypted Opus payload; contents are not retained.
     * @param client_timestamp_ms Wrapping client monotonic millisecond timestamp.
     * @param extended_sequence Wrap-aware admitted packet sequence.
     * @param arrival Host arrival time.
     */
    void record_accepted(std::span<const std::uint8_t> opus, std::uint32_t client_timestamp_ms, std::int64_t extended_sequence, std::chrono::steady_clock::time_point arrival) noexcept;

    /**
     * @brief Count one complete frame and aggregate real packet PCM.
     *
     * @param source Frame source.
     * @param pcm Mono samples; contents are not retained.
     */
    void record_frame(microphone_frame_source_e source, std::span<const std::int16_t> pcm) noexcept;

    /**
     * @brief Count one forward sequence reanchor.
     */
    void record_reanchor() noexcept;

    /**
     * @brief Count one full jitter-queue discard.
     */
    void record_jitter_overflow() noexcept;

    /**
     * @brief Count playout positions skipped after a scheduling delay.
     *
     * @param count Number of skipped positions.
     */
    void record_skipped(std::uint64_t count) noexcept;

    /**
     * @brief Count one frame refused by the sink mailbox.
     */
    void record_sink_drop() noexcept;

    /**
     * @brief Observe an interval between receiver loop checkpoints.
     *
     * @param gap Nonnegative checkpoint interval.
     */
    void record_schedule_gap(std::chrono::nanoseconds gap) noexcept;

    /**
     * @brief Return and reset the current reporting interval.
     * @return Aggregate snapshot for the completed interval.
     */
    microphone_diagnostics_snapshot_t take_interval() noexcept;

    /**
     * @brief Return session-wide counters without resetting them.
     * @return Aggregate snapshot for the full session so far.
     */
    [[nodiscard]] microphone_diagnostics_snapshot_t totals() const noexcept;

  private:
    microphone_diagnostics_snapshot_t interval_;  ///< Counters since the last report.
    microphone_diagnostics_snapshot_t totals_;  ///< Counters for the complete session.
    std::int64_t last_extended_sequence_ {-1};  ///< Newest sequence used for timing deltas.
    std::uint32_t last_client_timestamp_ms_ {};  ///< Timestamp paired with the newest sequence.
    std::chrono::steady_clock::time_point last_arrival_ {};  ///< Arrival paired with the newest sequence.
  };
}  // namespace remote_microphone::detail
